//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direction
    {
        public Direction()
        {
            this.LCIAs = new HashSet<LCIA>();
            this.ProcessFlows = new HashSet<ProcessFlow>();
        }
    
        public int DirectionID { get; set; }
        public string Direction1 { get; set; }
    
        public virtual ICollection<LCIA> LCIAs { get; set; }
        public virtual ICollection<ProcessFlow> ProcessFlows { get; set; }
    }
}
