//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flow
    {
        public Flow()
        {
            this.Processes = new HashSet<Process>();
        }
    
        public int FlowID { get; set; }
        public string FlowUUID { get; set; }
        public string FlowVersion { get; set; }
        public string Name { get; set; }
        public string CASNumber { get; set; }
        public Nullable<int> FlowPropertyID { get; set; }
        public Nullable<int> FlowTypeID { get; set; }
        public string FlowType_SQL { get; set; }
        public string ReferenceFlowProperty_SQL { get; set; }
    
        public virtual ICollection<Process> Processes { get; set; }
        public virtual FlowType FlowType { get; set; }
    }
}
