//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCIA
    {
        public int LCIAID { get; set; }
        public Nullable<int> LCIAMethodID { get; set; }
        public string LCIAUUID { get; set; }
        public Nullable<int> FlowID { get; set; }
        public Nullable<int> DirectionID { get; set; }
        public Nullable<double> Factor { get; set; }
        public string Flow_SQL { get; set; }
        public string Direction_SQL { get; set; }
    
        public virtual LCIAMethod LCIAMethod { get; set; }
        public virtual Direction Direction { get; set; }
    }
}
