//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCIAMethod_DUPE
    {
        public LCIAMethod_DUPE()
        {
            this.LCIA_DUPE = new HashSet<LCIA_DUPE>();
        }
    
        public string UUID { get; set; }
        public string Version { get; set; }
        public string LCIAMethod { get; set; }
        public string Methodology { get; set; }
        public string ImpactCategory { get; set; }
        public string ImpactIndicator { get; set; }
        public string ReferenceYear { get; set; }
        public string Duration { get; set; }
        public string ImpactLocation { get; set; }
        public string IndicatorType { get; set; }
        public bool Normalization { get; set; }
        public bool Weighting { get; set; }
        public string UseAdvice { get; set; }
        public string Source { get; set; }
        public string ReferenceQuantity { get; set; }
    
        public virtual ICollection<LCIA_DUPE> LCIA_DUPE { get; set; }
    }
}
