//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackgroundFragment
    {
        public int BackgroundFragmentID { get; set; }
        public Nullable<int> BackgroundID { get; set; }
        public Nullable<int> FragmentID { get; set; }
    
        public virtual Background Background { get; set; }
        public virtual Fragment Fragment { get; set; }
    }
}
