//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategorySystem
    {
        public CategorySystem()
        {
            this.Categories = new HashSet<Category>();
            this.Classifications = new HashSet<Classification>();
        }
    
        public int CategorySystemID { get; set; }
        public string CategorySystem1 { get; set; }
        public string URI { get; set; }
        public Nullable<int> DataTypeID { get; set; }
        public string Delimeter { get; set; }
        public string DataType_SQL { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Classification> Classifications { get; set; }
        public virtual DataType DataType { get; set; }
    }
}
