//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Classifications = new HashSet<Classification>();
        }
    
        public int CategoryID { get; set; }
        public string ExternalClassID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CategorySystemID { get; set; }
        public Nullable<int> ParentClassID { get; set; }
        public Nullable<int> HierarchyLevel { get; set; }
    
        public virtual ICollection<Classification> Classifications { get; set; }
    }
}
