//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int CategoryID { get; set; }
        public Nullable<int> CategorySystemID { get; set; }
        public Nullable<int> CategoryClassID { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> HierarchyLevel { get; set; }
        public string Hier { get; set; }
    
        public virtual CategorySystem CategorySystem { get; set; }
        public virtual Class Class { get; set; }
    }
}
