//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategorySystem
    {
        public int CategorySystemID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DataTypeID { get; set; }
        public string Delimeter { get; set; }
    
        public virtual DataType DataType { get; set; }
    }
}
