//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Categories = new HashSet<Category>();
            this.Classifications = new HashSet<Classification>();
        }
    
        public int ID { get; set; }
        public string ClassID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> CategorySystemID_SQL { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Classification> Classifications { get; set; }
    }
}
