//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classification
    {
        public int ClassificationID { get; set; }
        public string ClassificationUUID { get; set; }
        public Nullable<int> CategorySystemID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string ClassID_SQL { get; set; }
        public string CategorySystem_SQL { get; set; }
    
        public virtual CategorySystem CategorySystem { get; set; }
        public virtual Class Class { get; set; }
    }
}
