//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompostionModel
    {
        public CompostionModel()
        {
            this.CompositionDatas = new HashSet<CompositionData>();
        }
    
        public int CompositionModelID { get; set; }
        public Nullable<int> FlowID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CompositionData> CompositionDatas { get; set; }
        public virtual Flow Flow { get; set; }
    }
}
