//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DependencyParam
    {
        public DependencyParam()
        {
            this.DistributionParams = new HashSet<DistributionParam>();
            this.DistributionParams1 = new HashSet<DistributionParam>();
        }
    
        public int DependencyParamID { get; set; }
        public Nullable<int> ParamID { get; set; }
        public Nullable<int> FragmentEdgeID { get; set; }
    
        public virtual FragmentEdge FragmentEdge { get; set; }
        public virtual Param Param { get; set; }
        public virtual ICollection<DistributionParam> DistributionParams { get; set; }
        public virtual ICollection<DistributionParam> DistributionParams1 { get; set; }
    }
}
