//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributionParam
    {
        public int DistributionParamID { get; set; }
        public Nullable<int> DependencyParamID { get; set; }
        public Nullable<int> ConservationParamID { get; set; }
    
        public virtual DependencyParam DependencyParam { get; set; }
        public virtual DependencyParam DependencyParam1 { get; set; }
    }
}
