//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowPropertyVersion
    {
        public int FlowPropertyVersionID { get; set; }
        public int FlowPropertyVersionFlowID { get; set; }
        public int FlowPropertyVersionFlowPropertyID { get; set; }
        public Nullable<double> MeanValue { get; set; }
        public Nullable<double> StDev { get; set; }
    
        public virtual Flow Flow { get; set; }
        public virtual FlowProperty FlowProperty { get; set; }
    }
}
