//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowProperty
    {
        public FlowProperty()
        {
            this.Flows = new HashSet<Flow>();
            this.FlowPropertyEmissions = new HashSet<FlowPropertyEmission>();
            this.FragmentNodes = new HashSet<FragmentNode>();
            this.LCIAMethods = new HashSet<LCIAMethod>();
            this.NodeDissipations = new HashSet<NodeDissipation>();
        }
    
        public int FlowPropertyID { get; set; }
        public string FlowPropertyUUID { get; set; }
        public string Name { get; set; }
        public Nullable<int> UnitGroupID { get; set; }
    
        public virtual ICollection<Flow> Flows { get; set; }
        public virtual ILCDEntity ILCDEntity { get; set; }
        public virtual UnitGroup UnitGroup { get; set; }
        public virtual ICollection<FlowPropertyEmission> FlowPropertyEmissions { get; set; }
        public virtual ICollection<FragmentNode> FragmentNodes { get; set; }
        public virtual ICollection<LCIAMethod> LCIAMethods { get; set; }
        public virtual ICollection<NodeDissipation> NodeDissipations { get; set; }
    }
}
