//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowFlowProperty
    {
        public FlowFlowProperty()
        {
            this.CompositionDatas = new HashSet<CompositionData>();
            this.CompositionParams = new HashSet<CompositionParam>();
            this.FlowPropertyParams = new HashSet<FlowPropertyParam>();
        }
    
        public int FlowFlowPropertyID { get; set; }
        public Nullable<int> FlowID { get; set; }
        public Nullable<int> FlowPropertyID { get; set; }
        public Nullable<double> MeanValue { get; set; }
        public Nullable<double> StDev { get; set; }
    
        public virtual ICollection<CompositionData> CompositionDatas { get; set; }
        public virtual ICollection<CompositionParam> CompositionParams { get; set; }
        public virtual Flow Flow { get; set; }
        public virtual ICollection<FlowPropertyParam> FlowPropertyParams { get; set; }
    }
}
