//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowFlowProperty
    {
        public int FlowPropertyVersionID { get; set; }
        public string FlowPropertyVersionUUID { get; set; }
        public Nullable<int> FlowID { get; set; }
        public Nullable<int> FlowPropertyID { get; set; }
        public Nullable<double> MeanValue { get; set; }
        public Nullable<double> StDev { get; set; }
        public string FlowReference_SQL { get; set; }
        public Nullable<int> Ind_SQL { get; set; }
    
        public virtual Flow Flow { get; set; }
    }
}
