//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowProperty
    {
        public FlowProperty()
        {
            this.Flows = new HashSet<Flow>();
            this.FlowPropertyVersions = new HashSet<FlowPropertyVersion>();
            this.LCIAMethods = new HashSet<LCIAMethod>();
        }
    
        public int FlowPropertyID { get; set; }
        public string FlowPropertyUUID { get; set; }
        public string FlowPropertyVersion { get; set; }
        public string FlowProperty1 { get; set; }
        public Nullable<int> FlowPropertyUnitGroupID { get; set; }
        public string UnitGroup_SQL { get; set; }
    
        public virtual ICollection<Flow> Flows { get; set; }
        public virtual UnitGroup UnitGroup { get; set; }
        public virtual ICollection<FlowPropertyVersion> FlowPropertyVersions { get; set; }
        public virtual ICollection<LCIAMethod> LCIAMethods { get; set; }
    }
}
