//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowPropertyEmission
    {
        public int FlowPropertyEmissionID { get; set; }
        public Nullable<int> FlowPropertyID { get; set; }
        public Nullable<int> EmissionID { get; set; }
        public Nullable<double> Scale { get; set; }
    
        public virtual Flow Flow { get; set; }
        public virtual FlowProperty FlowProperty { get; set; }
    }
}
