//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowPropertyParam
    {
        public int FlowPropertyParamID { get; set; }
        public Nullable<int> ParamID { get; set; }
        public Nullable<int> FlowFlowPropertyID { get; set; }
    
        public virtual FlowFlowProperty FlowFlowProperty { get; set; }
        public virtual FlowPropertyParam FlowPropertyParam1 { get; set; }
        public virtual FlowPropertyParam FlowPropertyParam2 { get; set; }
    }
}
