//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fragment
    {
        public Fragment()
        {
            this.BackgroundFragments = new HashSet<BackgroundFragment>();
            this.FragmentEdges = new HashSet<FragmentEdge>();
            this.FragmentStages = new HashSet<FragmentStage>();
        }
    
        public int FragmentID { get; set; }
        public string Name { get; set; }
        public Nullable<int> RootNode { get; set; }
        public Nullable<int> ReferenceFlow { get; set; }
    
        public virtual ICollection<BackgroundFragment> BackgroundFragments { get; set; }
        public virtual Flow Flow { get; set; }
        public virtual ICollection<FragmentEdge> FragmentEdges { get; set; }
        public virtual ICollection<FragmentStage> FragmentStages { get; set; }
    }
}
