//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FragmentEdge
    {
        public FragmentEdge()
        {
            this.DependencyParams = new HashSet<DependencyParam>();
        }
    
        public int FragmentEdgeID { get; set; }
        public Nullable<int> FragmentID { get; set; }
        public Nullable<int> Origin { get; set; }
        public Nullable<int> FlowID { get; set; }
        public Nullable<int> DirectionID { get; set; }
        public Nullable<int> Terminus { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual ICollection<DependencyParam> DependencyParams { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual Flow Flow { get; set; }
        public virtual Fragment Fragment { get; set; }
        public virtual FragmentEdge FragmentEdge1 { get; set; }
        public virtual FragmentEdge FragmentEdge2 { get; set; }
        public virtual FragmentNode FragmentNode { get; set; }
        public virtual FragmentNode FragmentNode1 { get; set; }
    }
}
