//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FragmentNode
    {
        public FragmentNode()
        {
            this.FragmentEdges = new HashSet<FragmentEdge>();
            this.FragmentEdges1 = new HashSet<FragmentEdge>();
            this.FragmentNodeFragments = new HashSet<FragmentNodeFragment>();
            this.NodeDissipations = new HashSet<NodeDissipation>();
            this.NodeEmissions = new HashSet<NodeEmission>();
        }
    
        public int FragmentNodeID { get; set; }
        public Nullable<int> FragmentID { get; set; }
        public string Name { get; set; }
        public Nullable<int> FragmentStageID { get; set; }
        public Nullable<int> ReferenceProperty { get; set; }
        public Nullable<int> NodeTypeID { get; set; }
    
        public virtual FlowProperty FlowProperty { get; set; }
        public virtual ICollection<FragmentEdge> FragmentEdges { get; set; }
        public virtual ICollection<FragmentEdge> FragmentEdges1 { get; set; }
        public virtual FragmentStage FragmentStage { get; set; }
        public virtual FragmentStage FragmentStage1 { get; set; }
        public virtual NodeType NodeType { get; set; }
        public virtual ICollection<FragmentNodeFragment> FragmentNodeFragments { get; set; }
        public virtual ICollection<NodeDissipation> NodeDissipations { get; set; }
        public virtual ICollection<NodeEmission> NodeEmissions { get; set; }
    }
}
