//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FragmentScore
    {
        public int FragmentScoreID { get; set; }
        public Nullable<int> FragmentID { get; set; }
        public Nullable<int> LCIAMethodID { get; set; }
        public Nullable<int> FragmentNodeStageID { get; set; }
        public Nullable<int> ScenarioID { get; set; }
        public Nullable<int> ParamID { get; set; }
        public Nullable<double> ImpactScore { get; set; }
    }
}
