//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FragmentStage
    {
        public FragmentStage()
        {
            this.FragmentNodes = new HashSet<FragmentNode>();
            this.FragmentNodes1 = new HashSet<FragmentNode>();
        }
    
        public int FragmentStageID { get; set; }
        public Nullable<int> FragmentID { get; set; }
        public string StageName { get; set; }
    
        public virtual Fragment Fragment { get; set; }
        public virtual ICollection<FragmentNode> FragmentNodes { get; set; }
        public virtual ICollection<FragmentNode> FragmentNodes1 { get; set; }
    }
}
