//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILCDEntity
    {
        public ILCDEntity()
        {
            this.Classifications = new HashSet<Classification>();
            this.Flows = new HashSet<Flow>();
            this.FlowProperties = new HashSet<FlowProperty>();
            this.LCIAMethods = new HashSet<LCIAMethod>();
            this.Processes = new HashSet<Process>();
            this.UnitGroups = new HashSet<UnitGroup>();
        }
    
        public string UUID { get; set; }
        public string Version { get; set; }
        public Nullable<int> DataProviderID { get; set; }
        public Nullable<int> DataTypeID { get; set; }
    
        public virtual ICollection<Classification> Classifications { get; set; }
        public virtual DataProvider DataProvider { get; set; }
        public virtual DataType DataType { get; set; }
        public virtual ICollection<Flow> Flows { get; set; }
        public virtual ICollection<FlowProperty> FlowProperties { get; set; }
        public virtual ICollection<LCIAMethod> LCIAMethods { get; set; }
        public virtual ICollection<Process> Processes { get; set; }
        public virtual ICollection<UnitGroup> UnitGroups { get; set; }
    }
}
