//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCIAMethod
    {
        public LCIAMethod()
        {
            this.LCIAs = new HashSet<LCIA>();
        }
    
        public int LCIAMethodID { get; set; }
        public string LCIAMethodUUID { get; set; }
        public string LCIAMethodVersion { get; set; }
        public string Name { get; set; }
        public string Methodology { get; set; }
        
        public Nullable<int> ImpactCategoryID { get; set; }
        public string ImpactIndicator { get; set; }
        public string ReferenceYear { get; set; }
        public string Duration { get; set; }
        public string ImpactLocation { get; set; }
        public Nullable<int> IndicatorTypeID { get; set; }
        public Nullable<bool> Normalization { get; set; }
        public Nullable<bool> Weighting { get; set; }
        public string UseAdvice { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> FlowPropertyID { get; set; }
        public string Source { get; set; }
        public string ReferenceQuantity { get; set; }
    
        public virtual ICollection<LCIA> LCIAs { get; set; }
    }
}
