//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCIA
    {
        public int LCIAID { get; set; }
        public Nullable<int> LCIAMethodID { get; set; }
        public Nullable<int> LCIAFlowID { get; set; }
        public Nullable<int> LCIADirectionID { get; set; }
        public Nullable<double> Factor { get; set; }
    
        public virtual Direction Direction { get; set; }
        public virtual Flow Flow { get; set; }
        public virtual LCIAMethod LCIAMethod { get; set; }
    }
}
