//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterLCAModel
    {
        public int MasterLCAModelID { get; set; }
        public Nullable<int> UUlID { get; set; }
        public string Version { get; set; }
        public string DataType { get; set; }
        public string URI { get; set; }
        public string OldIndex { get; set; }
    }
}
