//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodeType
    {
        public NodeType()
        {
            this.Backgrounds = new HashSet<Background>();
            this.FragmentNodes = new HashSet<FragmentNode>();
            this.ScenarioBackgrounds = new HashSet<ScenarioBackground>();
        }
    
        public int NodeTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Background> Backgrounds { get; set; }
        public virtual ICollection<FragmentNode> FragmentNodes { get; set; }
        public virtual ICollection<ScenarioBackground> ScenarioBackgrounds { get; set; }
    }
}
