//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodeEmission
    {
        public NodeEmission()
        {
            this.NodeEmissionParams = new HashSet<NodeEmissionParam>();
        }
    
        public int NodeEmissionID { get; set; }
        public Nullable<int> FragmentNodeID { get; set; }
        public Nullable<int> FlowID { get; set; }
        public Nullable<int> DirectionID { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual Direction Direction { get; set; }
        public virtual Flow Flow { get; set; }
        public virtual FragmentNode FragmentNode { get; set; }
        public virtual ICollection<NodeEmissionParam> NodeEmissionParams { get; set; }
    }
}
