//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Param
    {
        public Param()
        {
            this.CharacterizationParams = new HashSet<CharacterizationParam>();
            this.CompositionParams = new HashSet<CompositionParam>();
            this.DependencyParams = new HashSet<DependencyParam>();
            this.NodeDissipationParams = new HashSet<NodeDissipationParam>();
            this.NodeEmissionParams = new HashSet<NodeEmissionParam>();
            this.ProcessDissipationParams = new HashSet<ProcessDissipationParam>();
            this.ProcessEmissionParams = new HashSet<ProcessEmissionParam>();
        }
    
        public int ParamID { get; set; }
        public Nullable<int> ParamTypeID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Typ { get; set; }
        public Nullable<double> Max { get; set; }
    
        public virtual ICollection<CharacterizationParam> CharacterizationParams { get; set; }
        public virtual ICollection<CompositionParam> CompositionParams { get; set; }
        public virtual ICollection<DependencyParam> DependencyParams { get; set; }
        public virtual ICollection<NodeDissipationParam> NodeDissipationParams { get; set; }
        public virtual ICollection<NodeEmissionParam> NodeEmissionParams { get; set; }
        public virtual ParamType ParamType { get; set; }
        public virtual ICollection<ProcessDissipationParam> ProcessDissipationParams { get; set; }
        public virtual ICollection<ProcessEmissionParam> ProcessEmissionParams { get; set; }
        public virtual ScenarioParam ScenarioParam { get; set; }
    }
}
