//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        public Process()
        {
            this.BackgroundProcesses = new HashSet<BackgroundProcess>();
            this.FragmentNodeProcesses = new HashSet<FragmentNodeProcess>();
            this.ProcessFlows = new HashSet<ProcessFlow>();
        }
    
        public int ProcessID { get; set; }
        public string ProcessUUID { get; set; }
        public string Name { get; set; }
        public string Year { get; set; }
        public string Geography { get; set; }
        public Nullable<int> ReferenceTypeID { get; set; }
        public Nullable<int> ProcessTypeID { get; set; }
        public Nullable<int> ReferenceFlowID { get; set; }
    
        public virtual ICollection<BackgroundProcess> BackgroundProcesses { get; set; }
        public virtual Flow Flow { get; set; }
        public virtual ICollection<FragmentNodeProcess> FragmentNodeProcesses { get; set; }
        public virtual ILCDEntity ILCDEntity { get; set; }
        public virtual ProcessType ProcessType { get; set; }
        public virtual ReferenceType ReferenceType { get; set; }
        public virtual ICollection<ProcessFlow> ProcessFlows { get; set; }
    }
}
