//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        public Process()
        {
            this.ProcessFlows = new HashSet<ProcessFlow>();
        }
    
        public int ProcessID { get; set; }
        public Nullable<int> ProcessUUID { get; set; }
        public Nullable<int> ProcessVersion { get; set; }
        public string Process1 { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geography { get; set; }
        public Nullable<int> ReferenceFlow { get; set; }
        public string RefererenceType { get; set; }
        public string ProcessType { get; set; }
        public string Diagram { get; set; }
    
        public virtual ICollection<ProcessFlow> ProcessFlows { get; set; }
    }
}
