//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessDissipation
    {
        public ProcessDissipation()
        {
            this.ProcessDissipationParams = new HashSet<ProcessDissipationParam>();
        }
    
        public int ProcessDissipationID { get; set; }
        public Nullable<int> ProcessFlowID { get; set; }
        public Nullable<int> FlowPropertyEmissionID { get; set; }
        public Nullable<double> EmissionFactor { get; set; }
    
        public virtual ProcessFlow ProcessFlow { get; set; }
        public virtual ICollection<ProcessDissipationParam> ProcessDissipationParams { get; set; }
    }
}
