//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenarioGroup
    {
        public ScenarioGroup()
        {
            this.Scenarios = new HashSet<Scenario>();
        }
    
        public int ScenarioGroupID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string Name { get; set; }
        public string Visibility { get; set; }
    
        public virtual ICollection<Scenario> Scenarios { get; set; }
        public virtual User User { get; set; }
    }
}
