//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenario
    {
        public Scenario()
        {
            this.ScenarioBackgrounds = new HashSet<ScenarioBackground>();
        }
    
        public int ScenarioID { get; set; }
        public Nullable<int> ScenarioGroupID { get; set; }
        public string Name { get; set; }
    
        public virtual ScenarioGroup ScenarioGroup { get; set; }
        public virtual ICollection<ScenarioBackground> ScenarioBackgrounds { get; set; }
    }
}
