//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenarioBackground
    {
        public int ScenarioBackgroundID { get; set; }
        public Nullable<int> ScenarioID { get; set; }
        public Nullable<int> FlowID { get; set; }
        public Nullable<int> NodeTypeID { get; set; }
        public Nullable<int> TargetID { get; set; }
    
        public virtual Flow Flow { get; set; }
        public virtual NodeType NodeType { get; set; }
        public virtual Scenario Scenario { get; set; }
    }
}
