//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public Source()
        {
            this.LCIAMethods = new HashSet<LCIAMethod>();
        }
    
        public int SourceID { get; set; }
        public string SourceUUID { get; set; }
        public string SourceVersion { get; set; }
        public string Source1 { get; set; }
        public string Citation { get; set; }
        public string PubType { get; set; }
        public string URI { get; set; }
    
        public virtual ICollection<LCIAMethod> LCIAMethods { get; set; }
    }
}
