//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitGroup
    {
        public UnitGroup()
        {
            this.FlowProperties = new HashSet<FlowProperty>();
            this.UnitConversions = new HashSet<UnitConversion>();
        }
    
        public int UnitGroupID { get; set; }
        public string UnitGroupUUID { get; set; }
        public string Name { get; set; }
        public string ReferenceUnit { get; set; }
        public Nullable<int> ReferenceUnitConversionID { get; set; }
    
        public virtual ICollection<FlowProperty> FlowProperties { get; set; }
        public virtual ILCDEntity ILCDEntity { get; set; }
        public virtual ICollection<UnitConversion> UnitConversions { get; set; }
        public virtual UnitConversion UnitConversion { get; set; }
    }
}
