//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitConversion
    {
        public UnitConversion()
        {
            this.UnitGroups = new HashSet<UnitGroup>();
        }
    
        public int UnitConversionID { get; set; }
        public string Unit { get; set; }
        public Nullable<int> UnitGroupID { get; set; }
        public string LongName { get; set; }
        public Nullable<double> Conversion { get; set; }
    
        public virtual UnitGroup UnitGroup { get; set; }
        public virtual ICollection<UnitGroup> UnitGroups { get; set; }
    }
}
