//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCIATool.Models.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ScenarioGroups = new HashSet<ScenarioGroup>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> CanLogin { get; set; }
        public Nullable<bool> CanEditScenarios { get; set; }
        public Nullable<bool> CanEditFragments { get; set; }
        public Nullable<bool> CanEditBackground { get; set; }
        public Nullable<bool> CanAppend { get; set; }
    
        public virtual ICollection<ScenarioGroup> ScenarioGroups { get; set; }
    }
}
