// <auto-generated />
namespace LcaDataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FK_FlowFlowProperty_FlowProperty_Fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FK_FlowFlowProperty_FlowProperty_Fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201407022035013_FK_FlowFlowProperty_FlowProperty_Fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
