// <auto-generated />
namespace LcaDataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class IX_ILCDEntity_UUID_Version : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IX_ILCDEntity_UUID_Version));
        
        string IMigrationMetadata.Id
        {
            get { return "201408192235574_IX_ILCDEntity_UUID_Version"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
